### ISSUE TITLE
 When I create the project package the plugin is not working

### ISSUE THREAD

**Issue by christianstamati** [getnamo/udp-ue4#10]
Hello everyone,
my name is Christian I'm a student (so I don't have experience in this field) and for my thesis I would like to use this plugin to make an android app which I can use to send data to the Game created with the Engine... I was testing and I found these problems: https://youtu.be/Ur1MrrfmEJ8 You can check this video and see all the steps that I did. I don't know If I messed up or It's a bug... If you could help to solve this problem It would be amazing I love this plugin and I'm sure that It's possible to do a lot of cool things!!
Thank you!

**Comment by getnamo** [comment]
That video had problematic music for me (couldn't see it in US region), but after VPN I see you have an issue with packaging. I just packaged the latest build (v0.6.0) for win64 and tested an echo server https://gist.github.com/getnamo/8117fdc64209af086ce0337310c52a51) and it worked as expected on the same computer. Can you confirm the issue remains when you run the server on the same computer as the packaged ue4 client?

Keep in mind that this is a very simple plugin wrapping around UDP. If you want easy communication that works in android, I'd recommend using the websocket based https://github.com/getnamo/socketio-client-ue4

**Comment by christianstamati** [comment]
Hi! I'm really sorry about the music! So In this video: https://youtu.be/PQa7sjBSjnw I reinstalled everything from scratch and I tested the script that you provided to me and I also tested my android app that I'm currently working on... My goal is very simple I just want share the position of my phone with Google ArCore and then send the data to Unreal in order to make a virtual camera... The only problem is that when I build the ue4 project sending and receiving it's not possible... The plugin in the engine it's working perfectly! It's seems there is a compiling problem. Thank you very much for your time! I hope there is a solution!

**Comment by christianstamati** [comment]
Here are some specs about my system if you need them.
![1000](https://user-images.githubusercontent.com/48362853/79083445-b06b2180-7d2e-11ea-8c3e-775513011776.PNG)

And here are the folder structure of the plugin:
https://youtu.be/T_0butW-viE

I have Installed Visual Studio 2019.

**Comment by getnamo** [comment]
I believe the problem is you're using a blueprint only project with project plugins. For packaging to work you need to convert the project to mixed (C++ and blueprint). See https://github.com/getnamo/socketio-client-ue4#github for a how to; basically you just need to add a C++ class to your project to convert it to mixed, which will then include the plugins in the compilation step.

**Comment by christianstamati** [comment]
Hi, It's me again. So basically I tried to convert my project to C++ and I created a new class as you suggested in the guide, the problem now is that It's not compiling, and If I make the project with C++ template It will not let me create the package. I tried to build the project from VS and is telling me that Async.h is not in the directory you can see the steps in this video: https://youtu.be/jWYnLHIgy_k

VISUAL STUDIO BUILD:
![MissingAsync](https://user-images.githubusercontent.com/48362853/79144529-6b430000-7dbf-11ea-899a-7489976ad55b.PNG)

**Comment by getnamo** [comment]
Looks like this is related to the v2 build settings. Added some include fixes here: https://github.com/getnamo/udp-ue4/commit/7df845d0a9ed307fe818d8bc50dc52ff5ce4042d, pull latest or grab the updated release at https://github.com/getnamo/udp-ue4/releases/tag/0.6.1 and try again

**Comment by christianstamati** [comment]
Hi! 
It works like magic! Thank you very much for helping me! You are a really great developer and you were very quick at answering to me! I hope to see more of your stuff in the future! Thank you again, and have a good day! Ciao!
