### ISSUE TITLE
The problem with the packaging

### ISSUE THREAD

**Issue by freeman0407** [getnamo/udp-ue4#11]
Good afternoon! I am using version 4.24, UDP works in the project, but after packaging UDP does not work.
![3](https://user-images.githubusercontent.com/54231671/81386771-02854400-912f-11ea-9396-cb05c7c0c6d3.png)
![1](https://user-images.githubusercontent.com/54231671/81386777-03b67100-912f-11ea-8ef2-c4411f40a8df.png)
![2](https://user-images.githubusercontent.com/54231671/81386781-044f0780-912f-11ea-9aa8-0141f0050b9d.png)

**Comment by getnamo** [comment]
Try re-pulling latest to see if this has been fixed

**Comment by getnamo** [comment]
Working release https://github.com/getnamo/udp-ue4/releases/tag/1.0.0. Re-open if issue still present.
