### ISSUE TITLE
OnReceiveBytes does not seem to receive anything

### ISSUE THREAD

**Issue by fwerre** [getnamo/udp-ue4#12]
Hi,

just started to explore this useful plugin.

Sending data via Emit() works perfectly, but I am unable to receive any data. IP / Port is set correctly. Wireshark shows that data is arriving on the machine.

I followed all explanations but no success.
Is there anything I must do except set IP / Port and wait for the OnReceiveBytes() event?

Thanks in advance,
best regards,

fwerre

**Comment by getnamo** [comment]
Make sure your component is set to auto-listen to your port in default properties, or if you don't use that, start listening manually as described in https://github.com/getnamo/udp-ue4#how-to-use---basics

**Comment by fwerre** [comment]
Thanks getnamo,

I tried both, but no success. It seems that OnReceiveBytes() never fires an event.
Is there any way to debug this? As said, data is definitely arriving on the machine / IP / port

Fwerre

**Comment by getnamo** [comment]
I'd recommend testing it locally on the same machine first with e.g. https://gist.github.com/getnamo/8117fdc64209af086ce0337310c52a51 and sending data and waiting for echo response. That should show both paths working. If it works locally, try again over LAN, then if that works try over public IP. This way you can ensure there isn't a firewall blocking the data. Also keep in mind that ports are exclusive, so if another program is using that port it may be stealing it from your unreal project when it attempts to listen to it.

**Comment by fwerre** [comment]
Thanks a lot, the node echo server was really helpful to prove all is working correctly.

The reason for my problem was I messed up the receive / transmit ports, 

Thanks again for your help!
fwerre
