### ISSUE TITLE
Packaging does not work with latest version on 4.26

### ISSUE THREAD

**Issue by baldurg** [getnamo/udp-ue4#17]
![image](https://user-images.githubusercontent.com/225764/111802095-87033000-88c5-11eb-8f6c-74da9b693996.png)
I am using the latest release, downloaded and unzipped into my Plugins directory as usual.
When I run my project in the editor, everything works. When I package my project for Win64, packaging is successful but when I try to run the packaged project I get this error.
Plugin 'SocketIOClient' failed to load because module 'SIOJson' could not be found.

**Comment by getnamo** [comment]
If you're using a blueprint only project, you need to convert project to mixed (via adding dummy c++ class). See this section for details: https://github.com/getnamo/socketio-client-ue4#github

It's a limitation of blueprint only projects without pre-compiled static libs with plugins outside of the engine.

**Comment by baldurg** [comment]
Thank you. I don't know why I didn't come across this issue before, and I found nothing when searching for a possible cause.

**Comment by getnamo** [comment]
No worries it's a common issue, but rare enough unless you use plugins outside of marketplace. Anytime you find _plugin x failed to load because module y could not be found_, it usually indicates missing compiled build for that plugin.
