### ISSUE TITLE
Can decode a json message sent from python socket

### ISSUE THREAD

**Issue by Guocode** [getnamo/udp-ue4#19]
![image](https://user-images.githubusercontent.com/29799967/114263389-bb2ac600-9a17-11eb-81a2-a43755a882bc.png)
this is my python code
![image](https://user-images.githubusercontent.com/29799967/114263403-d1d11d00-9a17-11eb-8ee8-4bc46d183f68.png)
this is the bp

![image](https://user-images.githubusercontent.com/29799967/114263413-e1506600-9a17-11eb-9e0d-a5caebcaa93e.png)
I can receive the string, but i seems to be failed to decode to a json object, where is the problem?

**Comment by Guocode** [comment]
it's ok now

![image](https://user-images.githubusercontent.com/29799967/114264613-85d5a680-9a1e-11eb-921d-07921ea47fa8.png)

**Comment by getnamo** [comment]
See https://github.com/getnamo/socketio-client-ue4#decoding-responses for more detailed options on how to decode your message as this plugin depends on socket.io for json operations.

In particular I recommend you make a Struct that matches your message object type e.g. ```eye_left``` etc members with float params and then directly decode to that object using ```JsonObjectToStruct```.
