### ISSUE TITLE
Doesnt work after project packaged

### ISSUE THREAD

**Issue by yanfeiwong** [getnamo/udp-ue4#2]
Cant send or receive after project get packaged, but every thing works just fine in the editor.

**Comment by getnamo** [comment]
Interesting, never tried to package this simple plugin. Do you have any logs or errors that can help trace the discrepancy?

**Comment by yanfeiwong** [comment]
Solved, seems like need some change on "UDPWrapper.uplugin" file:
"Installed": true,
"Type": "Runtime",

**Comment by getnamo** [comment]
Excellent catch, I must've forgotten to change it when initially setting up the plugin. The update has now been made to uplugin in master branch to reflect that https://github.com/getnamo/udp-ue4/commit/02f35978a0250073493b14b9874a84d38dc4f6e7.
