### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by Xinyue312** [getnamo/udp-ue4#20]
When I dragged Plugins folder into my project folder, there popped out an error window titled "Missing RobotEngine Modules" and it said "the following modules are missing or built with a different engine version: SocketIOClient, SIOJson, SocketIOLib, CoreUtility, SIOJEditorPlugin, UDPWrapper."

Then when I tried to to rebuild them, it failed and said that I should rebuild manually from the source.

**Comment by getnamo** [comment]
use the .7z in releases not source code, which includes the binaries for your project
