### ISSUE TITLE
Crashing when sending UDP message without explicitly opening send/receive sockets

### ISSUE THREAD

**Issue by antanaris** [getnamo/udp-ue4#21]
Hi!

Game was crashing when sending UDP message without explicitly opening send/receive sockets. 
"By default the udp actor component will auto open both send and receive sockets on begin play." -- they didn't.

And a bit more info on this from the UE4 packaging log
`UATHelper: Packaging (Windows (64-bit)):   LogClass: Warning: BoolProperty FUDPSettings::bIsReceiveOpen is not initialized properly. Module:UDPWrapper File:Public/UDPComponent.h`
`UATHelper: Packaging (Windows (64-bit)):   LogClass: Warning: BoolProperty FUDPSettings::bIsSendOpen is not initialized properly. Module:UDPWrapper File:Public/UDPComponent.h`

Using UE 4.26.2 on a Windows 64 machine

Once explicitly opened sockets in actor's Construction Script, everything worked great.

**Comment by getnamo** [comment]
re-pull master and see if https://github.com/getnamo/udp-ue4/commit/90c5b08dd0a44bfbe3eef5fb2625aea7ca99baeb fixes the packaging issue

**Comment by antanaris** [comment]
Thank you, yes, [90c5b08 ](https://github.com/getnamo/udp-ue4/commit/90c5b08dd0a44bfbe3eef5fb2625aea7ca99baeb) fixed the packaging warnings

But not the crash when sending a message 

Unhandled Exception: EXCEPTION_ACCESS_VIOLATION reading address 0x0000000000000000
```
UE4Editor_UDPWrapper!FUDPNative::EmitBytes() [D:\Projects\Unreal Engine\***\Plugins\udp-ue4\Source\UDPWrapper\Private\UDPComponent.cpp:209]
UE4Editor_UDPWrapper!UUDPComponent::execEmitBytes() [D:\Projects\Unreal Engine\***\Plugins\udp-ue4\Intermediate\Build\Win64\UE4Editor\Inc\UDPWrapper\UDPComponent.gen.cpp:445]
```
