### ISSUE TITLE
Can I build this plugin for UE 4.27 or above?

### ISSUE THREAD

**Issue by 0xinfinite** [getnamo/udp-ue4#23]
Thanks to this plugin, I made a specific project that using UDP.
But if I upgrade project above 4.27, can I use this plugin?

I created a new project in 4.27 and tried to install this plugin on that project, re-build was failed.
Is there any way to re-build this plugin above 4.27? If it can't, can you tell me why it can't?

**Comment by getnamo** [comment]
If you include the plugin in a c++ project it will compile it along with a project, see notes on changing bp to mixed project here: https://github.com/getnamo/socketio-client-ue4#github.

Current master branch should compile for UE5.0, if it doesn't compile, provide error output log from visual studio.

**Comment by 0xinfinite** [comment]
I confirmed that plugin can be compiled properly. It seems that there was another problem.
It's a relief that can compile for UE5. Thank you very much.
