### ISSUE TITLE
Socket field access violation

### ISSUE THREAD

**Issue by Gnitry** [getnamo/udp-ue4#3]
Unreal Engine editor very often crashed with access violation because the field ReceiverSocket (or SenderSocked, i don't remember now...) was not initialized in the constructor.

The following code in the constructor helped me:

```
SenderSocket = nullptr;
ReceiveSocket = nullptr;
```

**Comment by getnamo** [comment]
Yeah in debug builds uninitialized fields can be problematic, make a pull request and I'll merge it.

**Comment by getnamo** [comment]
fix merged in https://github.com/getnamo/udp-ue4/pull/4
