### ISSUE TITLE
Async delegate call causing random crashes in pie

### ISSUE THREAD

**Issue by LucasMoskun** [getnamo/udp-ue4#5]
`AsyncTask(ENamedThreads::GameThread, [&, Data]()
{
			OnReceivedBytes.Broadcast(Data);
})`

Is causing random crashes when starting/stopping PIE. I am using unreal engine 4.21, and running pie as dedicated server. I have been unable to track the bug down to a root cause, however it goes away when commenting out these lines. The errors triggering visual studio exceptions in DebugGame Editor mode are inconsistent.

**Comment by getnamo** [comment]
Got any logs from the crashes?
