### ISSUE TITLE
bytes array conversion

### ISSUE THREAD

**Issue by Furin** [getnamo/udp-ue4#9]
Hi there.

I'm trying to use this plugin, but I'm having a really hard time converting from string to bytes array and bytes array to string. In the example screenshots you are showing a `To Bytes (string)` node, but I'm unable to find that in my blueprints right-click options. Am I missing a library for that? Or is there something else I need to do to make that show up?

Thank you.

**Comment by getnamo** [comment]
If you're using releases then you should also have the socket.io client plugin which has the conversion utility functions.
